apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: asapd-lite
  namespace: kube-system
  labels:
    k8s-app: asapd-lite
spec:
  selector:
    matchLabels:
      k8s-app: asapd-lite
  template:
    metadata:
      labels:
        k8s-app: asapd-lite
    spec:
      priorityClassName: system-node-critical
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.kubernetes.io/instance-type
                    operator: In
                    values:
                      - a4x-maxgpu-4g-metal
                      - a4x-maxgpu-4g-metal-nolssd
                  - key: cloud.google.com/gke-os-distribution
                    operator: In
                    values:
                      - cos
      tolerations:
      - operator: Exists

      containers:
      - name: asapd-lite
        image: us-docker.pkg.dev/gce-ai-infra/asapd-lite/asapd-lite:v0.0.2
        command: ["/usr/local/bin/run_asapd_lite.sh"]
        env:
        - name: LD_LIBRARY_PATH
          value: /asapd-lite/controller
        livenessProbe:
          httpGet:
            path: /healthz
            port: 19540
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            path: /healthz
            port: 19540

        securityContext:
          # 'privileged: true' is required for modifying most host-level
          # resources, including network devices and udev rules.
          privileged: true

        volumeMounts:
        - name: host-sys
          mountPath: /sys
        - name: host-proc
          mountPath: /proc
        - name: host-udev-rules
          mountPath: /usr/lib/udev/rules.d
        - name: host-run-udev
          mountPath: /run/udev
        - name: host-run-asapd-lite
          mountPath: /run/asapd-lite
        - mountPath: /hugepages-2Mi
          name: hugepage-2mi
        - name: var-log-google-asapd-lite
          mountPath: /var/log/google/asapd-lite
        - name: var-lib-google-asapd-lite
          mountPath: /var/lib/google/asapd-lite
        - name: host-systemd-system
          mountPath: /etc/systemd/system
        - name: host-run-systemd
          mountPath: /run/systemd
        resources:
          limits:
            hugepages-2Mi: 8192Mi
            memory: 1024Mi

      volumes:
      - name: host-sys
        hostPath:
          path: /sys
      - name: host-proc
        hostPath:
          path: /proc
      - name: host-udev-rules
        hostPath:
          path: /usr/lib/udev/rules.d
      - name: host-run-udev
        hostPath:
          path: /run/udev
      - name: host-run-asapd-lite
        hostPath:
          path: /run/asapd-lite
          type: DirectoryOrCreate
      - name: hugepage-2mi
        emptyDir:
          medium: HugePages-2Mi
      - name: var-log-google-asapd-lite
        hostPath:
          path: /var/log/google/asapd-lite
          type: DirectoryOrCreate
      # Mount /var/lib/google/asapd-lite to provide a persistent location for
      # the ipam binary on the host, allowing it to be executed from the host.
      # This location was choosen based on this documentation
      # https://docs.cloud.google.com/container-optimized-os/docs/concepts/disks-and-filesystem#working_with_the_file_system
      # Hence, this may not necessarily be a suitable location for non-COS based
      # systems.
      - name: var-lib-google-asapd-lite
        hostPath:
          path: /var/lib/google/asapd-lite
          type: DirectoryOrCreate
      - name: host-systemd-system
        hostPath:
          path: /etc/systemd/system
      - name: host-run-systemd
        hostPath:
          path: /run/systemd
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1%